# Generated by Django 5.0.2 on 2024-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'admin_registration',
                'managed': True,
            },
        ),
    ]
