# Generated by Django 5.0.2 on 2024-03-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_adminregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRegistration',
        ),
    ]
