# Generated by Django 5.0.2 on 2024-03-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='confirm_password',
        ),
    ]
