# Generated by Django 5.0.2 on 2024-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userregistration_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
